hetznercloud/csi-driver

README.md, deploy/kubernetes/hcloud-csi.yml, src/driver/controller.go, src/driver/controller_test.go, src/driver/driver.go, src/driver/helper.go, src/driver/node.go
=> Implement topology awareness

src/api/volume.go, src/driver/controller.go, src/driver/controller_test.go
From the spec:
// The ID of the node. This field is OPTIONAL. The CO SHOULD set this
// field to match the node ID returned by `NodeGetInfo` or leave it
// unset. If the value is set, the SP MUST unpublish the volume from
// the specified node. If the value is unset, the SP MUST unpublish
// the volume from all nodes it is published to.
string node_id = 2;
Fixes #13.
=> Handle unpublish call with empty node ID correctly

Dockerfile
Currently, XFS volume creation fails with an error:
```
May 29 00:32:51 dockerd-current[14528]: E0528 21:32:51.575423       1 mount_linux.go:495] format of disk "/dev/disk/by-id/scsi-0HC_Volume_26xxxxx" failed: type:("xfs") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-c711522b
May 29 00:32:51 kubelet[15598]: E0529 00:32:51.576309   15598 csi_attacher.go:320] kubernetes.io/csi: attacher.MountDevice failed: rpc error: code = Internal desc = failed to stage volume: executable file not found in $PATH
```
Installing xfsprogs into hcloud-csi-driver container fixes this problem.
=> Install xfsprogs into container

README.md
While starting using this driver with Kubernetes 1.14 I figured out that the README needs a few updates for 1.14.
=> README updates for Kubernetes 1.14

README.md, deploy/kubernetes/hcloud-csi-1.13.yml
- cluster-driver-registrar is no longer needed, instead being replaced
by manual declaration of the CSIDriver CRD.
- CSI sidecar images updated
- small README refactoring to account for version compatibilities
fixes #42
=> update deployment for k8s 1.14

CHANGES.md, src/api/volume.go, src/driver/controller.go, src/driver/controller_test.go, src/volumes/service.go
I'm currently running 1.1.4 on Kubernetes 1.14.4 and noticed that occasionally when I drain a node the pods failed to be restarted on the new node with errors like:
> AttachVolume.Attach failed for volume "pvc-9cd8dc0d-be90-11e9-929a-9600001f93a6" : rpc error: code = Internal desc = failed to publish volume: cannot perform operation because server is locked (locked)
> AttachVolume.Attach failed for volume "pvc-9cd8dc0d-be90-11e9-929a-9600001f93a6" : rpc error: code = Internal desc = failed to publish volume: volume is already attached to a server, please detach it first (service_error)
Hetzner Cloud Console showed the volume still being attached to the drained node and I had to manually detach the volume from the server to resolve the issue.
According to the logs, the volume seems to be …
=> Allow retry on attach/detach when server is locked

deploy/kubernetes/hcloud-csi-1.13.yml
This was forgotten when version 1.1.5 was released in cb459bfd5e7cad9751dac2026227754820abd664.
=> Use released version v1.1.5 in the hcloud-cs-1.13 deployment manifest

deploy/kubernetes/hcloud-csi-master.yml, deploy/kubernetes/hcloud-csi.yml
Kubernetes v1.16 clusters require access to the
csinodes.storage.k8s.io resource and PATCH rights to
volumeattachments.storage.k8s.io.
Fixes #65  and #77 
Signed-off-by: Christian Beneke <c.beneke@wirelab.org>
=> Fix rbac rules for kubernetes v1.16

deploy/kubernetes/hcloud-csi-master.yml, deploy/kubernetes/hcloud-csi.yml
The only non-patch bump is `csi-node-driver-registrar`, whose only change adds windows nodes support.
=> chore: bump k8s csi images

deploy/kubernetes/hcloud-csi-master.yml, deploy/kubernetes/hcloud-csi.yml
see: https://github.com/kubernetes-csi/cluster-driver-registrar
and:
https://kubernetes-csi.github.io/docs/csi-driver-object.html#what-creates-the-csidriver-object
This was added in #43 but reverted without explanation on 1a9edfaea5 (by
accident? What did I miss?)
=> remove deprecated csi-cluster-driver-registrar (again)

cmd/driver/main.go
Sometimes customers have problems to use the CSI driver because they entered the wrong API token. This should give them a better (and more helpful) error message.
=> Add api token length validation

cmd/driver/main.go
Currently there's no way to turn down logging verbosity for the csi-driver component. This can be a bit painful, especially due to request logging of healthchecks.
This PR adds an option to change log level verbosity using environment variable "LOG_LEVEL" which can be set to info,warn,error or debug. By default all log lines are logged (AllowAll) which is the same as the current behavior.
=> Add option to tune log verbosity

deploy/kubernetes/hcloud-csi-master.yml, deploy/kubernetes/hcloud-csi.yml
Today I created a new Kubernetes cluster (v1.19.4) on a Hetzner node. Everything worked in the normal way, except for a minor "cosmetic" issue when I setup the Hetzner `csi-driver` following the [README](https://github.com/hetznercloud/csi-driver#getting-started). At that point I saw the following warning:
```
$ kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v1.5.1/deploy/kubernetes/hcloud-csi.yml
Warning: storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
```
This PR is very simple and is intended to silence this warning by adopting the currently recommended `apiVersion`. I wanted to "scratch the itch" even if it's largely cosmetic for future Hetzner csi-driver users.
NOTE: I haven't tested this …
=> Chore: use recommended/latest CSIDriver apiVersion

deploy/kubernetes/hcloud-csi.yml
With v1.5.2, the csi-driver starts to prefix the version with a `v`.
This PR fixes the deloyment yaml file not being conformant with this change.
=> Fix image tag for v1.5.2

README.md, deploy/kubernetes/hcloud-csi-master.yml
We had issues in a hybrid cluster getting the CSI driver to work. It's easy to fix: don't deploy the CSI driver to the root server. This PR introduces a corresponding taint.
This is opened in response to [this issue](https://github.com/hetznercloud/csi-driver/issues/189).
=> Recognition of root servers

.github/workflows/test_e2e.yml, .gitlab-ci.yml, README.md
=> Remove testing for k8s 1.18 as written in our Versioning policy.

deploy/kubernetes/hcloud-csi-master.yml, deploy/kubernetes/hcloud-csi.yml
Changelogs:
* [external-attacher](https://github.com/kubernetes-csi/external-attacher/tree/master/CHANGELOG)
* [external-provisioner](https://github.com/kubernetes-csi/external-provisioner/tree/master/CHANGELOG)
* [external-resizer](https://github.com/kubernetes-csi/external-resizer/tree/master/CHANGELOG)
* [livenessprobe](https://github.com/kubernetes-csi/livenessprobe/blob/master/CHANGELOG)
* [node-driver-registrar](https://github.com/kubernetes-csi/node-driver-registrar/tree/master/CHANGELOG)
E2E test suite passes with these changes: https://github.com/samcday/csi-driver/actions/runs/1093866594
(by the way, it'd be great if CI was setup for PRs in this repository. I'm happy to help with that if there's interest in getting it running.)
=> Upgrade csi sidecars to latest versions.

e2etests/setup.go
This significantly sped up the e2e suite in CI, you can see an example [here](https://github.com/samcday/csi-driver/actions/runs/1089325239). Looks to be about a 2x speedup.
=> Run e2e tests in parallel.

.github/workflows/test_e2e.yml
These changes make it easy to run the e2e tests in CI from a fork. All the forked repo needs is a `HCLOUD_TOKEN` repository secret set.
=> Make e2e workflow friendly to running on forks.

driver/node.go, driver/node_test.go
This patch skips the filesystem expansion when the volume was requested
in blockstorage mode, preventing issues with unexpected filesystems.
This patch resolved the problem that even in blockstorage mode, the
hcloud-csi tires to run a filesystem expansion when extending the cloud
volume. This can fail for LUKS volumes or volumes using another
unsupported filesystem and prevent the PVC from ever be successfully
expanded.
The easiest way to prevent that is to not fiddling with the filesystem
when the volume is used in block device mode.
Fixes #208
=> Add exclude for blockstorage during resize

.github/workflows/test_e2e.yml, .gitlab-ci.yml, e2etests/setup.go, e2etests/templates/cloudinit_k8s.txt.tpl
This also moves the container runtime in our tests from docker to containerd
=> Add k8s 1.22 to tests

.dockerignore, .github/workflows/publish_on_master.yml, .github/workflows/publish_on_tag.yml, .github/workflows/test.yml, .github/workflows/test_e2e.yml
Cache Golang modules with actions/cache. This speeds up the unit tests
workflow about 3x (from ~1m30s to ~20s).
.dockerignore to ensure only code changes cause Docker context to change
and require a Golang rebuild.
Switch Docker builds to use official Docker images powered by BuildKit.
These builds run in parallel, and also cache layers between workflow
executions. The new builder, if hitting a fully primed cache, can finish
in 30 seconds (down from ~2-3m).
Images are tagged by scoping the Docker Hub organization to the repo
owner. Thus it's possible to fork the project and set DOCKER_USER +
DOCKER_PASSWORD in the fork environment and produce release artifacts
easily.
---
You can see some examples of the updated tag release CI here: …
=> CI improvements for speed and fork-friendliness.

cmd/driver/main.go, deploy/kubernetes/hcloud-csi-master.yml, deploy/kubernetes/hcloud-csi.yml, e2etests/setup.go
The debug logging is not useful for end-users. It's also quite spammy
because the regular liveness probes cause an endless amount of noise in
the logs.
During e2e testing it's much more useful, so we patch the deployment
to set the log level back to debug there.
closes #209
=> Reduce default log verbosity to info level

cmd/driver/main.go
Calling the API every second is not needed as most actions are done in less than three seconds, so we can easily save a few API requests here.
=> Increase default polling interval to 3 seconds.

.github/workflows/test_e2e.yml, e2etests/e2e_test.go, e2etests/setup.go
The concurrency changes bring test time down to ~15m, [as you can see here](https://github.com/samcday/csi-driver/actions/runs/1168306054).
I've noticed that pushing the concurrency any higher seems to trigger rate limiting or some kind of problem on the hcloud platform side - I see lots of attach/detach API calls that fail with "unknown_error".
A concurrency of 3 per node seems to be fairly stable. Could maybe push this concurrency higher since we have 3 nodes but I've noticed that scheduler seems reluctant to place the e2e test pods on the control plane node, so better to assume there's only 2 nodes available with a 3 node setup.
Also tried to setup e2e test runs for PRs here, but reverted it because fork workflow runs don't have access to secrets. There are ways to work around this, …
=> e2e test workflow improvements

README.md
The PR https://github.com/hetznercloud/csi-driver/pull/195 introduced `instance.hetzner.cloud/is-root-server` to indicate that the driver should not run in dedicated servers (root servers). However the instructions are incorrect and try to add a taint instead of a label.
This was recognized here: https://github.com/hetznercloud/csi-driver/issues/189#issuecomment-826488883
This PR corrects the corresponding instructions in README.md
=> fix docs:  taints vs label

.gitattributes, deploy/kubernetes/controller/kustomization.yaml, deploy/kubernetes/controller/service.yaml, deploy/kubernetes/controller/statefulset.yaml, deploy/kubernetes/core/csidriver.yaml, deploy/kubernetes/core/kustomization.yaml, deploy/kubernetes/core/rbac.yaml, deploy/kubernetes/core/storageclass.yaml, deploy/kubernetes/hcloud-csi.yml, deploy/kubernetes/kustomization.yaml, deploy/kubernetes/node/daemonset.yaml, deploy/kubernetes/node/kustomization.yaml, deploy/kubernetes/node/service.yaml
Why?
* Makes it possible to deploy individual parts of the CSI Driver to
support complex topologies. For example, running the controller from
outside of the cluster.
* Easier to maintain and review changes.
* Prepares for a cleaner separation between the controller and node,
which will become important in subsequent changes I will be making
imminently.
For now, the hcloud-csi.yml exists. However now it will be generated
with `kustomize build . > deploy/kubernetes/hcloud-csi.yml`. It is still
around for two reasons:
* The e2e tests expect it to be there, and I can't be bothered figuring
out the easiest way to get them to use Kustomize instead.
* Documentation still recommends to `kubectl apply -f hcloud-csi.yaml`
I intend to address both of these points in subsequent changes. So the …
=> [1/???] Split deployment manifests

deploy/kubernetes/controller/deployment.yaml, deploy/kubernetes/controller/kustomization.yaml, deploy/kubernetes/hcloud-csi.yml, e2etests/setup.go
The controller does not need to be a StatefulSet, it is not inherently
stateful. The various sidecars all perform leader election using the
standard k8s Lease approach.
As part of switching to Deployment, drop the governing serviceName field
which was referencing a non-existent Service anyway.
Also remove the node affinity preventing the Deployment from scheduling
replicas on Hetzner root servers. This is not necessary - the controller
should run on root servers just fine, since it's really just responsible
for issuing requests to Hetzner Cloud API in response to CSI Driver
requests. It's only the Node DaemonSet that should not be scheduled on
root servers.
Finally, drop the privileged security context - the controller is not
performing any privileged operations.
=> [3/???] Switch Controller to Deployment, plus other tweaks

deploy/kubernetes/controller/deployment.yaml, deploy/kubernetes/hcloud-csi.yml, deploy/kubernetes/node/daemonset.yaml, driver/controller.go, driver/controller_test.go, driver/node.go, driver/node_test.go, driver/sanity_test.go, mock/volume.go, volumes/mount.go
In the various Node stage/unstage/publish/unpublish methods there was an
established pattern of requiring the csi.Volume object so that an API
call could be made to look up the volume details from the Hetzner Cloud
API.
In most of the code paths (unstaging, unpublishing in particular), this
lookup is entirely unnecessary. In fact the returned Volume object was
not being used for anything other than a log.Debug call.
In the case of the stage/publish calls, the volume lookup provided the
required LinuxDevice field (so the Node driver knows where the volume
is actually located in /dev). In this case, however, the CSI spec offers
a better alternative - PublishContext.
The ControllerPublishVolume call is responsible for doing the actual
attach of a hcloud volume to a particular node. The …
=> [4/???] Remove hcloud API calls from most Node code paths

driver/node.go, driver/node_test.go, driver/sanity_test.go, mock/volume.go, volumes/resize.go
Similar to the earlier work to remove volume lookup API calls in the
other Node RPC code paths. In this case we're doing some slightly scary
stuff, but I promise you it's all very legit and above board.
For starters, instead of using the canonical LinuxDevice path from the
API response, we use the mount-utils package to determine the device
path from the given volume path (where the device is actually mounted).
This should be completely safe - there's a nice library method for it,
after all. And there should never be a situation where Linux doesn't
know *what* device is mounted at a given path. Further, the CSI spec
clearly states that NodeExpandVolume MUST be called after the Stage and
Publish calls. So we'll only ever be asked to expand a volume that has
already been mounted.
The other …
=> [6/???] Simplify node resize

README.md, deploy/kubernetes/controller/deployment.yaml, deploy/kubernetes/hcloud-csi.yml, deploy/kubernetes/node/daemonset.yaml, e2etests/templates/cloudinit_k8s.txt.tpl
We want to unify the name of the token between the Cloud Controller Manager & the CSI Driver. This is already as a preparation for the upcoming version 2 of the csi driver.
Fixes https://github.com/hetznercloud/csi-driver/issues/254
=> Rename secret for hcloud api token to `hcloud`

driver/node.go, driver/node_test.go, driver/sanity_test.go, mock/volume.go, volumes/mount.go
Since b770ef5 the desired filesystem type is provided to the hcloud API.
As such the formatting no longer happens during the Stage call, making
it entirely unnecessary. Instead, the prepared volume is mounted to the
target location kubelet ultimately wants in the NodePublishVolume RPC
method.
Even if we for some reason wanted to do more fancy stuff on the node
side (I hope not, the whole point of the current patch series is to
reduce the node behaviour down to as minimal as possible), I think that
could just be done during the publish call.
Honestly, it's a bit of a head-scratcher why the stage/unstage
capability exists at all. I guess there's some use case for it, but it
doesn't appear our needs are complex enough to require it.
=> [8/???] Remove Node Stage/Unstage capability

app/app.go
We generally recommend to not change this environment variable, but it was requested in https://github.com/hetznercloud/csi-driver/issues/274 and we use the same snippet already internally if we want to test something.
Fixes https://github.com/hetznercloud/csi-driver/issues/274
=> Allow to configure the HCLOUD API Endpoint via Environment Variables.

Dockerfile, README.md, api/volume.go, driver/controller.go, driver/node.go, driver/node_test.go, driver/sanity_test.go, e2etests/testing.go, integrationtests/.gitignore, integrationtests/Dockerfile, integrationtests/cryptsetup_test.go, integrationtests/docker.go, integrationtests/integration_test.go, integrationtests/volumes_test.go, mock/volume.go, volumes/cryptsetup.go, volumes/idempotency.go, volumes/mount.go, volumes/resize.go, volumes/service.go
This PR adds full volume encryption. In short, one just has to add a new storage class referencing an encryption passphrase:
```yaml
apiVersion: v1
kind: Secret
metadata:
name: encryption-secret
namespace: kube-system
stringData:
encryption-passphrase: foobar
--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: hcloud-volumes-encrypted
provisioner: csi.hetzner.cloud
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
csi.storage.k8s.io/node-publish-secret-name: encryption-secret
csi.storage.k8s.io/node-publish-secret-namespace: kube-system
```
~~What is still missing is adjusting the e2e tests to also cover this (or do they already cover that case)?~~
Solves #40 and #163.
Note: ~~I did not make the PR against the latest …
=> Add support for volume encryption with cryptsetup and LUKS

.github/workflows/publish_on_master.yml
This should fix publishing unstable docker images and allow us to experiment with new features (e.g. #304)
=> ci: publish unstable docker image from main

README.md
Fix typo, where central branch was still called "master".
=> master --> main

integrationtests/volumes_test.go
The integration tests for the volume resize feature rely on specific byte amounts that a ext4 filesystem on a fake block device has. The specific amounts recently changed, probably through a new version of mkfs.ext4.
This amount equals the values from our GitHub Actions pipeline, as well as my local machine.
The amounts might need to be changed again in the future if the tests start failing again, we might consider removing tests for the specific amounts, and just check that the resized number is larger than the initial if this happens often.
=> test: fix integration tests relying on specific byte amounts

.github/workflows/test_e2e.yml, .gitlab-ci.yml, README.md
Update our tested-against Kubernetes versions to latest versions and add testing for Kubernetes v1.25.
Rebased on #322 to include fixes for integration tests.
=> feat: test against Kubernetes v1.25

driver/driver.go, driver/node.go
This change helps users that use multiple Hetzner Cloud locations in kubernetes clusters that manage nodes with [Cluster Autoscaler](https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-release-1.23/cluster-autoscaler/cloudprovider/hetzner).
All persistent volumes that are created with this driver has nodeAffinity:
```yaml
spec:
nodeAffinity:
required:
nodeSelectorTerms:
- matchExpressions:
- key: csi.hetzner.cloud/location
operator: In
values:
- <location>
```
If kubernetes cluster has nodes in multiple Hetzner Cloud location, autoscaler can not detect in which location, new server will be created for pods with such volume specs. Cluster Autoscaler use `topology.kubernetes.io/region` node label to detect in which location new servers are needed.
Signed-off-by: Maksim Paskal …
=> [enhancement] Use native kubernetes topology region label for volumes nodeAffinity

.github/workflows/publish_on_tag.yml, script/updateversion.bash
This version of the driver was not updated on new releases. This causes the user-agent to include the old version.
Concerns this line of code: https://github.com/hetznercloud/csi-driver/blob/main/driver/driver.go#L9
=> fix: driver version not updated on tagged release

driver/controller.go, driver/controller_test.go
Revert the topology segment label used for new volumes to `csi.hetzner.cloud/location`. Adding the new label was a mistake and leads to incompatibility with the CSI spec (and Nomad).
We plan to fully revert the changes, but that will require user intervention to fix all volumes created with the new label. By changing the label used on new volumes, we can limit the amount of volumes that need to be fixed for users that already upgraded to v2.0.0.
See issue #333 for details.
This is intended for `v2.0.1`
=> fix: invalid topology label on new volumes #333

driver/controller.go, driver/controller_test.go, driver/driver.go, driver/node.go
Revert all changes we made to our reported topology for nodes and volumes.
Because we report two segments on the `NodeGetInfo` call, but only one of them on `CreateVolume` we are not compliant with the CSI spec. This did not matter for Kubernetes, because the scheduler still worked, but it breaks Nomad.
As we are not compliant with the CSI spec, we decided to revert these changes, even though it will require user intervention to fix volumes created in the meantime.
For details see issue #333.
This is intended for v2.1.0
=> fix: revert invalid topology changes #333

Dockerfile
The resulting Docker image should have the same platform, no matter where it's built.
This change will make sure both the binaries and the base image are always `linux/amd64`.
I also updated the Alpline Linux image to 3.16, as 3.13 is approaching end of support.
=> Build the Docker image on any platform

e2etests/setup.go
NixOS does not provide scp under the previous path. By using `/usr/bin/env` we can automatically find scp from the PATH and execute that.
=> test: fix e2e suite for NixOS

driver/node.go, driver/node_test.go
When the VolumeAttachment was created with v1.6.0 (or older) it has an empty publish context and we run into a cryptic error during mount. We should always check that the device path is set in the publish context.
This will improve the error message for one of the bugs encountered in #278.
For details, see my comment: https://github.com/hetznercloud/csi-driver/issues/278#issuecomment-1351652816
=> fix(node): check for empty devicePath

docs/debug-logs.md
This document can be linked to in issues, so users have an easy to follow guide to activate the debug logs. Previously we copy&pasted the instructions in every issues where it was relevant.
=> docs: describe how to activate debug logs

hack/kustomization.yaml
In v2 we made multiple changes to our deployment manifests that were not
mirrored in the skaffold patches for local development:
- Remove hcloud token from node
- Use Deployment instead of StatefulSet for controller
This commit updates the skaffold patches to (better) work with the new
version.
=> refactor(skaffold): update manifests to match v2+ resources

.github/workflows/test_e2e.yml, .gitlab-ci.yml, README.md, e2etests/e2e_test.go
Add support for v1.26 and drop support for v1.22, in accordance with our Kubernetes version support policy (last 3 releases, same as upstream).
=> feat: test against Kubernetes v1.26

deploy/kubernetes/hcloud-csi.yml
Updated the full manifest by running: `kustomize build deploy/kubernetes > deploy/kubernetes/hcloud-csi.yml`
All new containers support kubernetes from 1.20 onwards.
https://github.com/kubernetes-csi/external-resizer/releases/tag/v1.7.0
https://github.com/kubernetes-csi/external-attacher/releases/tag/v4.1.0
https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.4.0
https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.7.0
https://github.com/kubernetes-csi/livenessprobe/releases/tag/v2.9.0
=> Update k8s sig-storage containers

integrationtests/docker.go, integrationtests/integration_test.go, integrationtests/volumes_test.go, volumes/mount.go
A recently introduced change (#279) caused block volumes to be formatted with ext4. This happened because setting the default for the FS type was moved from the non-Block Volume branch into the general code.
This PR reverts the move and adds a test to make sure that block storage is not accidentally formatted again in the future.
=> fix: Block volumes are formatted #349

README.md
Update docs to point to version [`v2.1.1`](https://github.com/hetznercloud/csi-driver/releases/tag/v2.1.1)
=> docs: update README for v2.1.1

volumes/cryptsetup.go
By default Hetzner Cloud uses thin provisioning for Volumes. This way, only the space that is actually used by the customer needs to be allocated in the storage pools.
Encrypting the volumes using LUKS breaks this thin provisioning, and the full amount needs to be allocated.
By setting allow-discards when mounting the volume, we tell the driver to use TRIM/discard, which re-enables the thin-provisioning for the volume.
This can be done when creating the LUKS partition, or when mounting it. By doing it on the mount, this will also be enabled for volumes that already exist prior to this commit when they are being re-attach anyway.
=> feat: set allow discards on luksOpen

deploy/kubernetes/controller/deployment.yaml, deploy/kubernetes/hcloud-csi.yml, deploy/kubernetes/node/daemonset.yaml
Closes #368 
Pull images from `registry.k8s.io` instead of `k8s.gcr.io`. The new registry supports multiple backends (Google Cloud & AWS so far) and should be preferred. At some point new releases for the sidecars wont be pushed to `k8s.gcr.io` anymore.
=> feat(k8s): pull CSI sidecar images from registry.k8s.io #368

README.md, docs/v2-fix-volumeattachments/fix-volumeattachments.sh
Provide script to prepare VolumeAttachments before migrating to v2.x.y of the csi-driver.
Closes #372
Related to one of the issues described in https://github.com/hetznercloud/csi-driver/issues/278#issuecomment-1351652816
=> docs(v2): describe process to prepare VolumeAttachments

app/app.go
By using exponential backoff we can reduce the number of API requests made, and better conserve our API rate limit.
Related to #346
Rebased on #379 as hcloud-go 1.40.0 added customizable polling backoff functions.
=> feat: use exponential backoff for action polling

deploy/kubernetes/controller/service.yaml, deploy/kubernetes/hcloud-csi.yml, deploy/kubernetes/service-monitor/kustomization.yaml, deploy/kubernetes/service-monitor/service-monitor.yaml, deploy/monitoring/grafana-dashboard.json, docs/monitoring.md
Add a default dashboard to visualize the exposed metrics as well as `ServiceMonitors` and a guide on how to set everything up.
Related to #346
=> feat: add Grafana dashboard and ServiceMonitors

cmd/controller/main.go
This PR adds support to execute the CSI controller on a node not hosted on the Hetzner Cloud. Additionally it reduces required API calls in this case as the location is already known at execution.
It adds a new environment variable `HCLOUD_VOLUME_DEFAULT_LOCATION` used for the controller service to work properly even without a server ID. It further implements changes requested at #282.
This is useful in a Gardener deployment where the "csi-driver-controller" is not necessarily deployed on a node in the Hetzner Cloud offering but still manages volumes for nodes deployed on the cloud.
=> Separate server ID from location for controller

.github/workflows/test_e2e.yml, e2etests/e2e_test.go
=> ci(e2e): improve behaviour in spite of flakiness

README.md
I have also removed the warning banner for users of `v2.0.0`, as it was up there for long enough and hopefully anyone that immediately deployed v2 also immediately deployed the follow up versions.
=> docs: Update README for v2.2.0

docs/v2-fix-volumeattachments/fix-volumeattachments.sh
With quotes, all IDs are in `$VOLUME_ATTACHMENT`.
=> Fix typo in Script: Remove quotes.

docs/v2-fix-volumeattachments/fix-volumeattachments.sh
The macos commands only accept the short form of the options.
=> Add volumeattachment script macos compatibility

docs/v2-fix-volumeattachments/fix-volumeattachments.sh
This change was required to have the array handled correctly at least on the bash version included in macos.
=> Fix volumeattachment array

.github/workflows/publish_on_master.yml
Fixes invalid arguments to `goreleaser`. Failed pipeline: https://github.com/hetznercloud/csi-driver/actions/runs/4666847571/jobs/8261917594#step:7:17
>    ⨯ command failed                                   error=unknown command "snapshot" for "goreleaser release"
=> ci: fix goreleaser arguments

.github/workflows/publish_on_tag.yml
Replace the deprecated `::set-output .*::` call using environment variables.
=> ci: replace deprecated ::set-output call

README.md, docs/nomad/README.md
=> docs: add nomad docs

.github/workflows/release-please.yml
Release-please created a PR for 1.7.0 instead of the correct 2.4.0 because the releases in between were done outside of the main branch.
I am not sure that this actually fixes the issue, but we will see once release-please runs.
=> ci: help release-please use the right latest release

.github/workflows/release-please.yml
Release v2.4.0 was successfully created. As we now have a good release, release-please will use that as the reference release for the future and we can remove all hardcoded references.
=> ci: cleanup release-please after succesful release

hack/dev-up.sh
The e2e tests fail regularly with [error message](https://github.com/hetznercloud/csi-driver/actions/runs/6155600692/job/16702755191?pr=491#step:7:63):
hcloud: network 3334615 has no free IP available or is in a different network zone (invalid_input)
As far as I can tell, this happens because the network does not yet have an available subnet when the server is created. With this change, we will wait until the network has the subnet (by grepping for the subnet cidr) before creating the server.
=> ci: fix flake in dev/e2e env where subnet is not available

.github/workflows/test_e2e.yml, docs/kubernetes/README.md, test/e2e/kubernetes/run-e2e-tests.sh, test/e2e/kubernetes/testdriver-1.25.yaml
In line with our [Kubernetes Versioning Policy](https://github.com/hetznercloud/csi-driver/tree/main/docs/kubernetes#versioning-policy).
=> feat: test against Kubernetes 1.28 and drop 1.24

chart/.snapshots/default.yaml, chart/.snapshots/example-prod.yaml, chart/.snapshots/full.yaml, chart/templates/controller/deployment.yaml, chart/templates/node/daemonset.yaml, deploy/kubernetes/hcloud-csi.yml, hack/update-deployment-yamls.sh
- two unecessary labels were added to the kubernetes manifests, these labels are helm specific/have a helm specific value.
- The image version in the rendered manifests did not update in the release-please PR, causing the manifests check to fail.
See https://github.com/hetznercloud/csi-driver/actions/runs/6339300867/job/17218138850?pr=493
=> ci: fix release-please issues with helm

.github/workflows/release-please.yml
This was missing from #508.
List of files taken by grepping for the marker. We do not need to include the`chart/templates` files, because they dont actually have the version. The marker in those files is only so it shows up in the rendered manifests.
```shell
$ grep -Hri "x-release-please-version"
chart/Chart.yaml:version: 2.4.0 # x-release-please-version
chart/.snapshots/example-prod.yaml:          image: docker.io/hetznercloud/hcloud-csi-driver:v2.4.0 # x-release-please-version
chart/.snapshots/example-prod.yaml:          image: docker.io/hetznercloud/hcloud-csi-driver:v2.4.0 # x-release-please-version
chart/.snapshots/full.yaml:          image: docker.io/hetznercloud/hcloud-csi-driver:v2.4.0 # x-release-please-version
chart/.snapshots/full.yaml:          image: …
```
=> ci: update version in all files that have release-please markers

.github/workflows/publish_on_tag.yml
See https://github.com/hetznercloud/csi-driver/actions/runs/6347875350/job/17243530008#step:8:66
The v2.5.0 release did not go through. The intent is to publish this as v2.5.1 ASAP.
=> fix: release workflow fails publishing with missing Git author

chart/README.md
The chart's name is not correct in the install documentation, this change sets the correct name
=> docs: fix chart name

chart/.snapshots/full.values.yaml, chart/.snapshots/full.yaml, chart/templates/node/daemonset.yaml, chart/values.schema.json, chart/values.yaml
This PR adds the config value node.kubeletDir to the helm chart to allow deploying the helm chart onto k8s distributions such as k0s. See e.g. #473
=> feat: add node.kubeletDir helm chart config value

chart/values.yaml, docs/kubernetes/README.md
Add some explanation about the kubelet dir value so users have an easier time figuring this out.
Related to #534
=> docs(k8s): non-standard kubelet dir (k0s, microk8s)

docs/nomad/README.md
Explains how to enable LUKS encryption for hcloud volumes.
=> docs: add instructions for LUKS encryption on Nomad

.github/workflows/test_e2e.yml, docs/kubernetes/README.md, test/e2e/kubernetes/run-e2e-tests.sh, test/e2e/kubernetes/testdriver.yaml
Kubernetes v1.25 is End of Life since 2023-10-28. In accordance with our Versioning policy.
=> feat: drop tests for kubernetes v1.25

.github/workflows/test.yml
Tests are currently only executed for PRs. This has two downsides:
- Coverage comparison in PRs is not available
- If two PRs modify similar code, they have the potential to break tests, this would only be discovered once a new PR is opened.
=> ci: run tests on main to get coverage comparison

.github/workflows/test.yml, hack/dev-up.sh
Hardcode versions of k3s to the last versions before the broken behaviour was introduced. We plan to unpin the versions after we figure out where the bug is coming from and fix it upstream.
=> test(e2e): new k3s versions break our dev/e2e test setup

README.md, hack/dev-up.sh
Learn more: https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-shared-intel-vcpus-are-deprecated
- Updated docs with newer server types
=> chore: replace deprecated server type with cx22

api/volume.go, api/volume_test.go, go.mod, go.sum, internal/mocked/mocked.go, volumes/idempotency.go, volumes/idempotency_test.go, volumes/service.go
If a previous resize attempt failed after calling `POST /v1/volumes/{id}/resize` (rate limit, network connectivity, ...), the volume might already have the target size.
The PVC (in Kubernetes) would still have the old size in its status, so the `external-resizer` makes another attempt at the resize. In the Hetzner Cloud API, a resize must always be larger than the current size, so the new resize failed with:
volume size is too small (invalid_input)
This is now fixed, as we compare the size of the Hetzner Cloud volume to the desired size and only proceed if an actual resize is needed.
This was a violation of the CSI Spec[0], which stated for `ControllerExpandVolume`:
> This operation MUST be idempotent. If a volume corresponding to the specified volume ID is already larger than or equal to …
=> fix(resize): recover from part-way failed resizes

.github/release-please-config.json
Missing update that didn't make it in #626
=> chore: fix missing `internal` path update

chart/templates/controller/deployment.yaml, chart/values.yaml, internal/app/app.go
This allows the `HCLOUD_TOKEN` to be read from a file. This can be useful if the token is injected using secret injection (e.g. with the vault agent injector).
I tested the changes on my dev cluster. If someone is interested in using this with the vault agent injector, I used the following helm values:
```yaml
controller:
hcloudToken:
file: /vault/secrets/token
image:
hcloudCSIDriver:
name: "" # path to custom image (because these changes here are not released)
rbac:
rules:
- apiGroups:
- authorization.k8s.io
resources:
- subjectaccessreviews
verbs:
- create
- apiGroups:
- authentication.k8s.io
resources:
- tokenreviews
verbs:
- create
podAnnotations:
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/log-format: json
vault.hashicorp.com/role: <your-vault-role-name> …
```
=> feat: read HCLOUD_TOKEN from file

.github/workflows/test.yml
Cancel outdated Kubernetes tests workflows, as they take a long time and it does not make sens to wait for each run to complete.
=> ci: cancel outdated kubernetes tests workflows

dev/hcloud-k8s-env/main-setup.tf
See https://github.com/renovatebot/renovate/pull/6631
No need for a custom regex manager.
=> chore: renovate already handles terraform helm releases

.github/workflows/test.yml
Remove all deployed resources to avoid running into limit errors.
=> ci: cleanup resources after e2e tests

.github/workflows/test.yml, docs/kubernetes/README.md, test/e2e/kubernetes/testdriver.yaml
- Add tests for Kubernetes 1.30 and claim compatibility in docs.
- Drop tests for Kubernetes 1.26 to match our Kubernetes support policy (only active releases). 1.26 became EOL on 2024-02-28.
BEGIN_COMMIT_OVERRIDE
feat(k8s): test against Kubernetes 1.30
feat(k8s): drop Kubernetes 1.26 from tests
END_COMMIT_OVERRIDE
=> feat(k8s): test against Kubernetes 1.30

chart/templates/_common_images.tpl, chart/templates/controller/deployment.yaml, chart/templates/node/daemonset.yaml, chart/values.schema.json, chart/values.yaml
This change allows the user to configure the image name separately from the image tag.
This is useful if you only want to change the image path (e.g. private image proxy) and not the tag.
The use of `.tag` is optional and will only be added is a value is set to maintain backward compatibility.
=> feat(chart): separate image name and tag

.github/workflows/test.yml, README.md, test/integration/cryptsetup_test.go, test/integration/docker.go, test/integration/integration_test.go, test/integration/volumes_test.go
The integration test need docker to run, we use a tag to filter out integrations tests in environment that do not have docker.
=> test: add integration test tag

internal/app/app.go
Related to #346 and #380
The initial exponential back off algorithm introduced in #380 was not truncated, which could lead to very long intervals. The recent release of hcloud-go truncated the default exponential back off algorithm to 60s: https://github.com/hetznercloud/hcloud-go/commit/fd1f46cc35e61dde1e524399eef88c38a757636e
If we take the scenario described in #346, I think we can still reduce the max interval value for the exponential back off algorithm to <30s.
=>  feat: truncate poll exponential backoff function to max 10s

.github/workflows/test.yml, docs/kubernetes/README.md, test/e2e/kubernetes/testdriver.yaml
Kubernetes v1.27 is End of Life since 2024-07-16. Removed from tests in accordance to our Kubernetes support policy (only active releases).
Also bumped to testdriver.yaml to specify capability that are available in 1.28+.
=> feat: drop tests for Kubernetes 1.27

internal/driver/controller_test.go, internal/driver/helper.go, test/e2e/kubernetes/Makefile
=> feat: Support SINGLE_NODE_MULTI_WRITER capability

chart/values.yaml, renovate.json
- Autogenerated references are not updated by renovate
- Only open pull requests if container images are actually present
=> chore: Fix renovate for container tags in generated files

internal/driver/controller.go, internal/driver/controller_test.go
See #327 
SINGLE_NODE_MULTI_WRITER needs to be in the response of the ControllerGetCapabilities function to correctly integrate support for SINGLE_NODE_MULTI_WRITER access modes.
This was missing from #725.
BEGIN_COMMIT_OVERRIDE
END_COMMIT_OVERRIDE
=> fix: updated capability response of the controller service

.github/workflows/lint.yml, .github/workflows/publish_on_master.yml, .github/workflows/publish_on_tag.yml, .github/workflows/test.yml, .gitlab-ci.yml, deploy/docker-swarm/pkg/Dockerfile, dev/Dockerfile, go.mod
This PR makes the CI pipeline use Go 1.23 for building and testing.
=> ci: build and test with Go 1.23

deploy/docker-swarm/pkg/config.json, internal/driver/node.go
With the merge of https://github.com/moby/swarmkit/pull/3116 the mock staging/unstaging is not needed anymore. It was introduced in our csi-driver in this commit: https://github.com/hetznercloud/csi-driver/commit/619fa5c3996e17e84b09deca0c956229e5554c77. Which is part of a large PR (squashed commit) that included experimental support for Docker swarm.
See:
- #376 
- #382
=> feat(swarm): removed workaround support for mock staging/unstaging

internal/driver/sanity_test.go, internal/mock/volume.go, internal/volumes/mount.go, test/integration/integration_test.go, test/integration/volumes_test.go
Replaced our code for formatting and other disk related functions to k8s.io/mount-utils. This leaves only code that is related to LUKS.
=> refactor: Switched to k8s.io/mount-utils

chart/.snapshots/default.yaml, chart/.snapshots/example-prod.yaml, chart/.snapshots/full.yaml, chart/templates/core/csidriver.yaml, deploy/kubernetes/hcloud-csi.yml
Mount options specified in the NodePublishVolumeRequest are already forwarded to /bin/mount (`-o context=<SELinux_Label>`). The /bin/mount binary included in our container image can detect whether the kernel supports SELinux.
The user still has to enable the feature gates `SELinuxMount` and `SELinuxMountReadWriteOncePod` in Kubernetes version `1.30`.
Further Reference:
- [KEP 1710](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1710-selinux-relabeling/README.md#volume-mounting)
- [What fields does the CSIDriver object have](https://kubernetes-csi.github.io/docs/csi-driver-object.html?highlight=SELinux#what-fields-does-the-csidriver-object-have)
- [Feature Gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha …
=> feat: support for SELinux mount

.github/workflows/test.yml
The 1.31 tests were using a test binary from 1.30.
=> test: using wrong k8s-test version for 1.31

.golangci.yaml
The exportloopref linter got deprecated and is no longer relevant since Go v1.22. It got replaced with the copyloopvar linter. Updated our golangci configuration.
=> chore: replaced deprecated linter

chart/.snapshots/default.yaml, chart/.snapshots/full.values.yaml, chart/.snapshots/full.yaml, chart/templates/core/storageclass.yaml, chart/values.yaml, deploy/kubernetes/hcloud-csi.yml, docs/kubernetes/README.md, internal/driver/driver.go, internal/driver/node.go
Due to a bug in the scheduler a node with no driver instance might be picked and the volume is stuck in pending as the "no capacity - > reschedule" recovery is never triggered [[0]](https://github.com/kubernetes/kubernetes/pull/122109), [[1]](https://github.com/kubernetes-csi/external-provisioner/issues/544).
- See #400
=> feat: force pods with volumes to be scheduled on Cloud servers

.github/workflows/test.yml
In our verify snapshots step, the git diff command is targeting the deploy/ directory instead of chart/.snapshots/.
=> ci: fixed verify snapshots using wrong path

internal/driver/controller.go, internal/driver/helper.go
Update PR of golangci-lint to v1.62.0 discovered a redefinition of cap in our capability check. Furthermore, we are shadowing cap in certain places.
Additionally, upgrade from v1.62.0 of golangci-lint (#774) can not be merged before this is fixed.
=> refactor: redefintion and shadowing of builtin id cap

chart/templates/core/storageclass.yaml, chart/values.yaml, docs/kubernetes/README.md, internal/driver/driver.go, internal/driver/node.go
We modified the response for `NodeGetInfo` to return an additional Topology Segment. We assumed that this only “adds” new info, but in practice it breaks the spec.
When trying to schedule a volume to nodes, the container orchestration systems should verify that the Node fulfills at least one Accessible Topology of the Node, where “fulfills” means that all supplied segments match.
This is not implemented in the same way between Kubernetes and Nomad.
- **Kubernetes**: requirements are fulfilled if the volume specifies a subset of the Nodes topology
- **Nomad**: requirements are fulfilled if the volume specifies all of the Nodes topology
We made these changes to work around a bug in the Kubernetes scheduler ([here](https://github.com/kubernetes-csi/external-provisioner/issues/544)) where …
=> fix: reverted NodeGetInfo response as it breaks Nomad clusters

chart/templates/controller/deployment.yaml, chart/templates/core/storageclass.yaml, chart/templates/node/daemonset.yaml, chart/values.yaml, cmd/aio/main.go, cmd/controller/main.go, cmd/node/main.go, docs/kubernetes/README.md, internal/app/app.go, internal/driver/controller.go, internal/driver/controller_test.go, internal/driver/driver.go, internal/driver/node.go, internal/driver/node_test.go, internal/driver/sanity_test.go
We are reintroducing a feature originally present in v2.10.0 to prevent pods from getting stuck in the `pending` state in clusters with non-cloud nodes. This feature is now optional and can be enabled via the Helm Chart. By default, it remains disabled to avoid compatibility issues with Nomad clusters, which have a different CSI spec implementation.
Learn more about it in #400.
=> feat: Added new option enableProvidedByTopology

cmd/controller/main.go, docs/kubernetes/README.md, internal/app/app.go
In our default strategy to fetch the default volume location there was an additional unnecessary request to the Hetzner API.
When fetching the location via the metadata service, we can directly utilize the availability zone provided by the service instead of using the server id to fetch the location and therefore making an additional request.
=> perf: reduced number of requests needed for fetching default volume location

.github/workflows/test.yml, docs/kubernetes/README.md
Kubernetes v1.28 is End of Life since 2024-10-22. In accordance with our Versioning policy.
=> feat: drop tests for kubernetes v1.28

docs/kubernetes/README.md
Version policy got oudated over time. Switching to `latest` instead of `vX.X.X+` as its less effort and consistent with other products.
=> docs: fixed outdated version policy

.github/workflows/test.yml
Adds scripts to our CI to capture the logs and events in Kubernetes and Nomad. These are exported as artifacts with the naming `debug-logs-k8s-XXX` and `debug-logs-nomad-XXX` where `XXX` is information about the current environment.
=> ci: export k8s logs and events from csi-driver

chart/templates/node/daemonset.yaml
Fixes a wrong ref in the charts daemonset manifest. Now uses `Values.node.extraVolumeMounts` instead of the controller mounts
=> fix: use extraVolumeMounts for node in daemonset

internal/driver/helper.go, test/e2e/kubernetes/testdriver.yaml
According to [KEP-2485](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/2485-read-write-once-pod-pv-access-mode/README.md#csi-specification-changes-volume-capabilities), if the csi-driver exposes the `SINGLE_NODE_MULTI_WRITER` capability, then `ReadWriteOncePod` will map to the `SINGLE_NODE_SINGLE_WRITER` volume capability, otherwise it will map to `SINGLE_NODE_WRITER`. Our controller already responded with the `SINGLE_NODE_MULTI_WRITER`, but we blocked `SINGLE_NODE_SINGLE_WRITER` in a validation step in the `ControllerPublishVolume` method.
Additional reference:
- https://kubernetes.io/blog/2021/09/13/read-write-once-pod-access-mode-alpha/#accept-new-csi-access-modes
- #327
=> feat: support ReadWriteOncePod

chart/templates/core/storageclass.yaml, chart/values.yaml
add the ability to set custom parameters for storageclass to enable e.g. luks disk encryption or set fstype
=> feat(helm-chart): add extraParam for StorageClass

docs/kubernetes/README.md
Kubernetes version v1.32 was missing from the table. New csi-driver version v2.12 was missing too.
=> docs: update version table

docs/kubernetes/how-to-import-volumes.md
Previously encrypted volumes need to reference the encryption secret in the PV spec. This PR extends the user guide.
Related issue: #922
=> docs: import encrypted volumes

README.md, docs/docker-swarm/README.md, docs/nomad/README.md
Closes #941 
This PR moves the unsupported lines (Docker Swarm, Nomand) to the buttom, so that the supported docs are more visible.
Result looks like this now: https://github.com/guettli/csi-driver/tree/tg/highlight-kubernetes-docs-more-clearly?tab=readme-ov-file#getting-started
=> docs: Highlight Kubernetes Docs More Clearly

.github/workflows/test.yml, test/e2e/kubernetes/Makefile
The `e2e.test` binary has __all__ kubernetes tests, but we only run those that start with `External.Storage`. This means there is a lot of "Skipped" output right now, that is useless. By setting `--silence-skips` these log lines are removed.
Additional ginkgo offers a `--github-output` flag that promises to make the output nicer for GitHub actions. Not sure what it really does.
These flags are only supported in Ginkgo 2.18+, which is only available in Kubernetes 1.31+.
=> ci(e2e): less ginkgo output

chart/.snapshots/full.yaml, chart/templates/node/daemonset.yaml
The value `node.extraVolumeMounts` should add those mounts to the `hcloud-csi-driver` container according to the docs. They were instead added to the `csi-node-driver-registrar` container.
=> fix(helm): node extraVolumeMounts are added to wrong container

.github/workflows/test.yml, .gitignore, cmd/aio/main.go, cmd/controller/main.go, cmd/node/main.go, dev/Dockerfile, hack/get-coverage-from-k8s.sh, internal/app/app.go, skaffold.yaml
In the dev env we now always include coverage in the built binaries.
We can send a `USR1` signal to the process to write it to a directory in the pod.
A script iterates over all pods, sends the signal and then pulls the coverage.
We combine the coverage for all node pods.
=> ci: evaluate coverage of e2e tests

dev/Dockerfile
Speeds up consecutive builds when using Skaffold during local development.
=> ci: cache go build artifacts in dev Dockerfile

internal/driver/controller.go, internal/driver/controller_test.go
After implementing the new label we have discovered an inconsistency in the Hetzner Cloud public API. The topic was discussed internally and as a result we have to remove the `csi.hetzner.cloud` prefix from the label. Besides, we have decided to rename the label to `managed-by`, as this is more consistent with other integrations (e.g., fleeting-plugin-hetzner). 
Additionally, the Kubernetes labels (e.g., `csi.storage.k8s.io/pvc/name`) are not valid, as there is a second `slash` in the key.
=> feat: rename default labels on Volumes

.github/workflows/lint.yml, .github/workflows/publish_on_master.yml, .github/workflows/publish_on_tag.yml, .github/workflows/test.yml
In #1076, we should have switched back to `go-version-file`. Since we want to extract the Go version from the toolchain directive in `go.mod`, we should follow the [docs](https://github.com/actions/setup-go/tree/v6.0.0?tab=readme-ov-file&utm_source=chatgpt.com#getting-go-version-from-the-gomod-file). The documentation is not very clear about the default behavior when using only `uses: actions/setup-go@v6`, so it seems safer to explicitly specify `go-version-file`.
=> ci: add go version file to setup-go
