src/api/volume.go

As we only compare the ID, there is no need to fetch the
server from the API.

Do not fetch server when detaching

---

src/volumes/idempotency.go
src/volumes/idempotency_test.go

I’m out of ideas for #12. 🤷‍♂️

Detach volume before deleting it

---

README.md

Add more info on how to setup (using C&P technique 🙈) the custom resources required for CRI

Improve info for base setup

---

README.md

Add step to apply the secret

---

CHANGES.md
api/volume.go
driver/controller.go
driver/controller_test.go

Fix wrong usage of Aborted error code

---

CHANGES.md
Dockerfile

Add `e2fsprogs-extra` to allow resizing of volumes

---

CHANGES.md
README.md
deploy/kubernetes/hcloud-csi.yml
driver/driver.go

Prepare Release v1.3.1

---

.gitlab-ci.yml
CHANGES.md
driver/node.go
driver/node_test.go
volumes/mount.go

Allow using raw block volumes

---

deploy/kubernetes/hcloud-csi-master.yml

Add tolerations to node csi driver

---

CHANGES.md
deploy/kubernetes/hcloud-csi-master.yml

Add label to metric services

---

CHANGES.md
cmd/driver/main.go
deploy/kubernetes/hcloud-csi-master.yml

The metadata service way will be still the recommended way.

Allow getting the server id through the server name

---

.github/workflows/test_e2e.yml
.gitlab-ci.yml

Update test versions to [ 1.17.13, 1.18.10, 1.19.3 ]

Update k8s version in e2e tests to the latest released versions

---

.github/workflows/goimports.yml
.github/workflows/publish_on_master.yml
.github/workflows/publish_on_tag.yml
.github/workflows/test.yml
.github/workflows/test_e2e.yml
.gitlab-ci.yml
CHANGES.md
Dockerfile
README.md
driver/sanity_test.go
go.mod

Update to go 1.16 and alpine 3.13

---

CHANGES.md
go.mod
go.sum

Update hcloud-go to 1.24.0

---

README.md

Note the fact that the volumes are ReadWriteOnce. Which was an open question to which #167 did not know the answer (and neither did I nor my co-worker), so I think it'd be good to mention that characteristic of the Volume right there :-)!

mention that volumes are ReadWriteOnce in the README.md

---

.github/workflows/bot_stale.yml
driver/node_test.go

Adjust stale bot to be more userfriendly

---

.github/workflows/publish_on_tag.yml
.goreleaser.yml
CHANGES.md

Use Goreleaser to publish changelog

---

.github/workflows/goimports.yml
.github/workflows/test.yml
.github/workflows/test_e2e.yml
.gitlab-ci.yml
Dockerfile
README.md
go.mod

Use Go 1.17

---

cmd/driver/main.go

Opted to filter out logging for Probe requests since the livenessprobe sidecar will freak out in informative ways if there's anything going wrong with that API call.

Include more information in request logging

---

cmd/driver/main.go

driver: fix panic when server is not found.

---

.github/workflows/test_e2e.yml

Use our own runners in E2E tests

---

deploy/kubernetes/hcloud-csi-master.yml
deploy/kubernetes/hcloud-csi.yml

[Green e2e build here](https://github.com/samcday/csi-driver/actions/runs/1169866312)

Remove unneeded privileges from CSI sidecars

---

README.md

Updates Version Constraint

---

Dockerfile
README.md
deploy/kustomization.yaml
hack/kustomization.yaml
skaffold.yaml

Next todos:
- introduce script for the test setup
Credits also goes to @samcday

Add skaffold for local debugging + add "Local test setup" section to README.md

---

README.md

Explicit docs: read+write API token is needed.

---

docs/v2.0.0-fix-volume-topology/fix-persistentvolume-topology.sh
docs/v2.0.0-fix-volume-topology/fix-volume-topology.md

See #333
Once this has been merged, I will update the issue to direct users to this guide.

docs: document procedure to fix PVs broken with v2.0.0

---

.github/workflows/test.yml

Verify hcloud-csi.yml is up-to-date

---

integrationtests/volumes_test.go

Instead of expecting exact byte values that have changed in the past the test now just asserts that the size roughly doubles.

Relax volume integration test

---

e2etests/setup.go

ci(e2e): fail fast on worker setup errors

---

.github/workflows/publish_on_master.yml
.github/workflows/publish_on_tag.yml
.gitignore
.goreleaser.yml
Dockerfile
hack/Dockerfile
skaffold.yaml

Switch our build pipeline to match hetznercloud/hcloud-cloud-controller-manager#417

feat(goreleaser): produce OCI manifest images

---

app/app.go
cmd/aio/main.go
cmd/controller/main.go
cmd/node/main.go
volumes/mount.go
volumes/resize.go

Hoping to improve the situation that leads to issues like #465. This will probably not fix it, but with the additional logs we might have better visibility into what goes wrong.
This PR contains 3 individual commits that improve different things.
Another related PR to metadata service reliability is hetznercloud/hcloud-go#293

fix: improve handling of metadata service connectivity

---

.github/workflows/publish_on_master.yml
.github/workflows/publish_on_tag.yml
deploy/docker-swarm/pkg/Dockerfile
deploy/docker-swarm/pkg/Makefile

(hopefully) fixes #428
What I did do:
- adapted the Makefile
- Checked if everything compiled properly
- adapted the GitHub Actions
What I did not do:
- Manually test on a Cloud Server for AMD64
- Manually test on a Cloud Server for ARM64

configure builds for arm64

---

docs/kubernetes/README.md

The helm chart is now available for some time without major issues. Additionally there is a number of options available only in the Helm chart, which improve the user experience.

docs(k8s): prefer helm installation method

---

chart/.snapshots/example-prod.yaml
chart/.snapshots/full.yaml
chart/templates/controller/clusterrole.yaml

fix(helm): missing rbac for leader election / leases

---

.github/workflows/test_e2e.yml
docs/kubernetes/README.md
test/e2e/kubernetes/run-e2e-tests.sh

Add the new version to our ci and docs matrices.

feat: add support & tests for Kubernetes 1.29

---

renovate.json

Ensure related packages are updated together.

chore: group csi spec and csi-test packages updates

---

Dockerfile
deploy/docker-swarm/pkg/Dockerfile
hack/Dockerfile
test/integration/Dockerfile

Improve readability, preparing for possible future changes.

style: improve dockerfile readability

---

README.md

Use smaller font for getting started table of content.

style: format readme

---

.github/workflows/publish_on_master.yml
.github/workflows/publish_on_tag.yml

Reuse the go version from the go.mod file.

ci: use go version from go.mod

---

chart/values.yaml

Keep the images in our chart up to date.

chore: renovate chart images

---

.goreleaser.yml

Publish the hcloud-csi-driver as an additional release artifact.

feat: publish binary
